spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jwt:
    secretKey: delivery0120
  datasource:
    url: jdbc:h2:mem:DB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace   # sql query 에 들어오는 파라메타 값 추적
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis: # Redis 접속 정보
    host: localhost
    port: 6380
